name: "@svelte-kitchen/monorepo"
description: "Svelte Kitchen"
private: true
license: "MPL-2.0"
author: "nuin"

scripts:
  test: >-
    echo "Error: no test specified" &&
    exit 1

packageManager: "pnpm@10.28.0"
engines:
  node: ">=24.0.0"
  pnpm: ">=10.0.0"
