name: "@svelte-kitchen/monorepo"
description: "Svelte Kitchen"
private: true
license: "MPL-2.0"
author: "nuin"

scripts:
  # Dev
  dev: pnpm "/^dev:.*/"
  dev:website: pnpm --filter website dev

  # Build
  build: pnpm "/^buidl:.*/"
  build:website: >-
    pnpm --filter website install &&
    pnpm --filter website build

  # Preview
  preview: pnpm build && wrangler dev

  # Linter / Formatter
  check: >-
    biome check ;
    dprint check
  format: >-
    biome format --write ;
    dprint fmt
  lint: biome lint --write

packageManager: "pnpm@10.28.0"
engines:
  node: ">=24.0.0"
  pnpm: ">=10.0.0"

devDependencies:
  "@biomejs/biome": "catalog:"
  dprint: "catalog:"
  wrangler: "catalog:"
