name: "@svelte-kitchen/monorepo"
description: "Svelte Kitchen"
private: true
license: "MPL-2.0"
author: "nuin"

scripts:
  # Dev
  dev: pnpm "/^dev:.*/"

  # Build
  build: pnpm "/^buidl:.*/"

  # Preview
  preview: pnpm build && wrangler dev

packageManager: "pnpm@10.28.0"
engines:
  node: ">=24.0.0"
  pnpm: ">=10.0.0"

devDependencies:
  wrangler: "catalog:"
