packages:
  - "apps/*"
  - "packages/*"
  - "website"

catalog:
  typescript: ^5.9.3
  vite: ^7.3.1
  wrangler: ^4.61.1

  # ----- Linter / Formatter -----
  "@biomejs/biome": 2.3.13
  dprint: ^0.51.1

  # ----- Test -----
  "@vitest/browser-playwright": ^4.0.18
  playwright: ^1.58.1
  vitest: ^4.0.18
  vitest-browser-svelte: 2.0.2

catalogs:
  svelte5:
    "@sveltejs/vite-plugin-svelte": ^6.2.4
    svelte: ^5.49.1
    svelte-check: ^4.3.6

  sveltekit2:
    "@sveltejs/adapter-static": ^3.0.10
    "@sveltejs/kit": ^2.50.1

onlyBuiltDependencies:
  - esbuild
