packages:
  - "apps/*"
  - "packages/*"
  - "website"

catalog:
  vite: ^7.3.1
  wrangler: ^4.61.1

  # ----- Linter / Formatter -----
  "@biomejs/biome": 2.3.13
  dprint: ^0.51.1

onlyBuiltDependencies:
  - esbuild
